// <auto-generated />
namespace InventorySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:InventorySystem/Migrations/202210211813438_d.Designer.cs
    public sealed partial class d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d));
        
        string IMigrationMetadata.Id
        {
            get { return "202210211813438_d"; }
========
    public sealed partial class ini : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ini));
        
        string IMigrationMetadata.Id
        {
            get { return "202210211617413_ini"; }
>>>>>>>> 46806822aaadf8949d1d6ba1491a7a2d6d4705cd:InventorySystem/Migrations/202210211617413_ini.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
